#!/usr/bin/env bash

set -euo pipefail

shopt -s nullglob

output_file="_generated/archives-by-year.md"
tmp_records="$(mktemp)"

trap 'rm -f "$tmp_records"' EXIT

slugify_post_name() {
  local value="$1"

  value="${value%.md}"
  value="${value//&/and}"
  value="${value// /-}"
  value="${value%.md}"

  printf '%s\n' "$value"
}

extract_front_matter_value() {
  local key="$1"
  local file="$2"

  awk -v key="$key" '
    BEGIN { in_front_matter = 0 }

    /^---[[:space:]]*$/ {
      if (!in_front_matter) {
        in_front_matter = 1
        next
      }

      exit
    }

    in_front_matter && $0 ~ "^" key ":[[:space:]]*" {
      sub("^" key ":[[:space:]]*", "")
      gsub(/^["'"'"']|["'"'"']$/, "")
      gsub(/^[[:space:]]+|[[:space:]]+$/, "")
      print
      exit
    }
  ' "$file"
}

mkdir -p "$(dirname "$output_file")"

for source in _posts/*.md; do
  base="${source##*/}"
  slug="${base#????-??-??-}"
  slug="$(slugify_post_name "$slug")"

  title="$(extract_front_matter_value title "$source")"
  date="$(extract_front_matter_value date "$source")"

  if [[ -z "$title" || -z "$date" ]]; then
    printf 'Missing title or date in %s\n' "$source" >&2
    exit 1
  fi

  printf '%s\t%s\t%s\n' "$date" "$slug" "$title" >> "$tmp_records"
done

{
  printf '<!-- Generated by scripts/generate-archives.sh. -->\n\n'

  if [[ ! -s "$tmp_records" ]]; then
    printf '_No posts yet._\n'
  else
    current_year=""

    while IFS=$'\t' read -r date slug title; do
      year="${date:0:4}"

      if [[ "$year" != "$current_year" ]]; then
        [[ -n "$current_year" ]] && printf '\n'
        printf '## %s\n' "$year"
        current_year="$year"
      fi

      safe_title="${title//[/\\[}"
      safe_title="${safe_title//]/\\]}"
      printf -- '- [%s](/posts/%s/) (%s)\n' "$safe_title" "$slug" "$date"
    done < <(LC_ALL=C sort -r "$tmp_records")
  fi
} > "$output_file"
